In [1]:
import cv2

In [2]:
img_g = cv2.imread("smallgray.png", 0)   # reading image to variable, 0: grayscale, 1: color (bgr)

In [3]:
img_g

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [4]:
cv2.imwrite("new_smallgray.png", img_g)  # writing the array into a new image

True

In [5]:
img_g[0:2]  # get the first 2 rows

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147]], dtype=uint8)

In [6]:
img_g[0:2, 2:4]  # get the first 2 rows, and from them columns (index) 2 and 3 (4 excluded)

array([[104, 121],
       [255, 255]], dtype=uint8)

In [7]:
img_g[1,1]  # get one item, 2nd row, 2nd column (indexes)

125

In [8]:
# iterating through the array
# iterate by rows: 
for i in img_g:
    print(i)

[187 158 104 121 143]
[198 125 255 255 147]
[209 134 255  97 182]


In [9]:
# iterate by columns (by transpose .T):
for i in img_g.T:
    print(i)

[187 198 209]
[158 125 134]
[104 255 255]
[121 255  97]
[143 147 182]


In [11]:
# iterate by each item:
for i in img_g.flat:
    print(i)

187
158
104
121
143
198
125
255
255
147
209
134
255
97
182


In [12]:
img_g

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [15]:
import numpy
# horizontal stacking - hstack, using a tuple as parameter
img_hs = numpy.hstack((img_g, img_g))  # saving to new variable, tuple could contain different arrays
print(img_hs)

[[187 158 104 121 143 187 158 104 121 143]
 [198 125 255 255 147 198 125 255 255 147]
 [209 134 255  97 182 209 134 255  97 182]]


In [17]:
# vertical stacking - vstack, using a tuple as parameter
img_vs = numpy.vstack((img_g, img_g, img_g))  # saving to new variable, tuple could contain different arrays
print(img_vs)

[[187 158 104 121 143]
 [198 125 255 255 147]
 [209 134 255  97 182]
 [187 158 104 121 143]
 [198 125 255 255 147]
 [209 134 255  97 182]
 [187 158 104 121 143]
 [198 125 255 255 147]
 [209 134 255  97 182]]


In [19]:
# spliting horizontally - by columns
# hsplit, the last parameter is divisor, the results must be same size (columns % number = 0)
h_split = numpy.hsplit(img_vs, 5)   # the result will be a python list of numpy arrays
print(h_split)
print(h_split[0])  # can reach each splitted array by indexing

[array([[187],
       [198],
       [209],
       [187],
       [198],
       [209],
       [187],
       [198],
       [209]], dtype=uint8), array([[158],
       [125],
       [134],
       [158],
       [125],
       [134],
       [158],
       [125],
       [134]], dtype=uint8), array([[104],
       [255],
       [255],
       [104],
       [255],
       [255],
       [104],
       [255],
       [255]], dtype=uint8), array([[121],
       [255],
       [ 97],
       [121],
       [255],
       [ 97],
       [121],
       [255],
       [ 97]], dtype=uint8), array([[143],
       [147],
       [182],
       [143],
       [147],
       [182],
       [143],
       [147],
       [182]], dtype=uint8)]
[[187]
 [198]
 [209]
 [187]
 [198]
 [209]
 [187]
 [198]
 [209]]


In [20]:
# spliting vertically - by rows
# vsplit, the last parameter is divisor, the results must be same size (rows % number = 0)
v_split = numpy.vsplit(img_vs, 3)   # the result will be a python list of numpy arrays
print(v_split)
print(v_split[0])  # can reach each splitted array by indexing

[array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8), array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8), array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)]
[[187 158 104 121 143]
 [198 125 255 255 147]
 [209 134 255  97 182]]
